services:
  database:
    container_name: database
    image: ${POSTGRES_IMAGE}
    ports:
      - ${DATABASE_PORT}
    volumes:
      - database:/var/lib/postgresql/data
      - ./database/init-database.sh:/docker-entrypoint-initdb.d/init-postgres.sh
    restart: always
    env_file:
      - path: ./database/.env

  postgres:
    container_name: postgres
    image: ${POSTGRES_IMAGE}
    ports:
      - ${POSTGRES_PORT}
    restart: always
    env_file:
      - path: ./airflow/.env

  init:
    container_name: init
    image: ${AIRFLOW_IMAGE}
    depends_on:
      - postgres
    env_file:
      - path: ./airflow/.env
    entrypoint: /bin/bash
    command: -c 'airflow db init && airflow users create --username ${USERNAME} --password ${PASSWORD} --firstname ${FIRSTNAME} --lastname ${LASTNAME} --role ${ROLE} --email ${EMAIL}'

  webserver:
    container_name: webserver
    image: ${AIRFLOW_IMAGE}
    ports:
      - ${WEBSERVER_PORT}
    restart: always
    depends_on:
      - postgres
    volumes:
      - logs:/opt/airflow/logs
    env_file:
      - path: ./airflow/.env
    command: webserver

  scheduler:
    container_name: scheduler
    image: ${AIRFLOW_IMAGE}
    restart: always
    depends_on:
      - postgres
    volumes:
      - logs:/opt/airflow/logs
      - ./airflow/dags:/opt/airflow/dags
      - ./query:/opt/airflow/query
    env_file:
      - path: ./airflow/.env
    command: scheduler

volumes:
  logs:
    driver: local
  database:
    driver: local

networks:
  default:
    name: dev-net
